apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-bridge
spec:
  config: |
    {
      "cniVersion": "1.1.0",
      "name": "br0",
      "type": "bridge",
      "bridge": "br0",
      "isGateway": true,
      "forceAddress": false,
      "ipMasq": true,
      "hairpinMode": true,
      "ipam":
      {
        "type": "host-local",
        "subnet": "10.10.0.0/24",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "dataDir": "/run/ipam/br0"
      }
    }
