apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipam-static
spec:
  config: |
    {
      "cniVersion": "1.1.0",
      "name": "stat0",
      "type": "bridge",
      "bridge": "stat0",
      "isGateway": true,
      "forceAddress": false,
      "hairpinMode": true,
      "ipam":
      {
        "type": "static",
        "addresses": [
          {
            "address": "172.168.30.20/24",
            "gateway": "172.168.30.1"
          },
          {
            "address": "172.168.10.10/24",
            "gateway": "172.168.10.1"
          },
          {
            "address": "172.168.110.200/24",
            "gateway": "172.168.110.1"
          }
        ],
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "dataDir": "/run/ipam/stat0"
      }
    }
