apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-3001
spec:
  config: |
    {
      "cniVersion": "1.1.0",
      "name": "vlan0",
      "type": "vlan",
      "master": "eth0",
      "vlanId": 3001,
      "ipam":
      {
        "type": "host-local",
        "subnet": "10.50.0.0/24",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "dataDir": "/run/ipam/vlan0"
      }
    }
