apiVersion: apps/v1
kind: Deployment
metadata:
  name: netutils-host-bridge
  labels:
    app: netutils-host-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      network-type: host-bridge
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: host-bridge
      labels:
        network-type: host-bridge
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: network-type
                    operator: In
                    values: ["host-bridge"]
              topologyKey: kubernetes.io/hostname
      containers:
        - name: netutils
          image: isim/netutils:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1
            requests:
              cpu: 0.1
