apiVersion: apps/v1
kind: Deployment
metadata:
  name: netutils
  labels:
    app: netutils
spec:
  replicas: 1
  selector:
    matchLabels:
      network-type: multus
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: ipam-local,ipam-static,br-vlan1901,br-vlan2050
      labels:
        network-type: multus
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: network-type
                    operator: In
                    values: ["multus"]
              topologyKey: kubernetes.io/hostname
      containers:
        - name: netutils
          image: isim/netutils:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1
            requests:
              cpu: 0.1
