apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        network-type: multus
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: network-type
                    operator: In
                    values: ["multus"]
              topologyKey: kubernetes.io/hostname
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: ipam-local
              bridge: {}
            - name: ipam-static
              bridge: {}
            - name: br-vlan1901
              bridge: {}
            - name: br-vlan2050
              bridge: {}
        resources:
          requests:
            memory: 5Gi
            cpu: 2
      readinessProbe:
        initialDelaySeconds: 120
        periodSeconds: 20
        timeoutSeconds: 10
        failureThreshold: 3
        successThreshold: 3
        httpGet:
          port: 80
      networks:
        - name: default
          pod: {}
        - name: ipam-local
          multus:
            networkName: ipam-local
        - name: ipam-static
          multus:
            networkName: ipam-static
        - name: br-vlan1901
          multus:
            networkName: br-vlan1901
        - name: br-vlan2050
          multus:
            networkName: brvlan-2050
      volumes:
        - name: containerdisk
          containerDisk:
            image: isim/ubuntu-containerdisk:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkDataSecretRef:
              name: netconfig
            secretRef:
              name: cloudinit
