apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-basic
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 5Gi
            cpu: 2
      readinessProbe:
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 10
        failureThreshold: 3
        successThreshold: 3
        httpGet:
          port: 80
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: isim/ubuntu-containerdisk:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: cloudinit
